# Generated by Django 3.2.4 on 2022-06-07 21:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='shop/media'), upload_to='products/%Y/%m/%d'),
        ),
    ]
